# Generated by Django 5.2.16 on 2026-07-27 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0002_alter_cluster_code_alter_cluster_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="master.indicator",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_scores",
                        to="master.village",
                    ),
                ),
            ],
            options={
                "ordering": ["indicator"],
            },
        ),
        migrations.CreateModel(
            name="VariableScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="master.variable",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable_scores",
                        to="master.village",
                    ),
                ),
            ],
            options={
                "ordering": ["variable"],
            },
        ),
        migrations.CreateModel(
            name="VillageScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "normalized_score",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("rank", models.PositiveIntegerField(default=0)),
                (
                    "village",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="village_score",
                        to="master.village",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
    ]
