# Generated by Django 5.2.16 on 2026-07-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_mlmodelregistry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmodelregistry",
            name="cluster_mapping",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mapping label KMeans (0,1,2,...) ke Cluster master (id, code, name, rank, mean_score).",
            ),
        ),
        migrations.AlterField(
            model_name="mlmodelregistry",
            name="feature_importance",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Hasil Random Forest feature importance per indikator, diurutkan dari yang paling dominan.",
            ),
        ),
        migrations.AlterField(
            model_name="mlmodelregistry",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Model registry aktif yang sedang dipakai sistem.",
            ),
        ),
        migrations.AlterField(
            model_name="mlmodelregistry",
            name="variable_importance",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Feature importance yang sudah diagregasi per variabel (X1, X2, ..., Y6) dalam bentuk persentase.",
            ),
        ),
    ]
