# Generated by Django 5.2.16 on 2026-08-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alter_mlmodelregistry_cluster_mapping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stale",
                    models.BooleanField(
                        default=False,
                        help_text="Ada perubahan konfigurasi variable yang belum dihitung ulang.",
                        verbose_name="Perlu hitung ulang",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Analysis State",
                "verbose_name_plural": "Analysis State",
            },
        ),
    ]
