# Generated by Django 5.2.16 on 2026-08-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_analysis_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisstate",
            name="stale",
        ),
        migrations.AddField(
            model_name="analysisstate",
            name="signature",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="Config Signature"
            ),
        ),
    ]
