# Generated by Django 5.2.16 on 2026-07-27 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_alter_cluster_code_alter_cluster_name_and_more'),
        ('respondent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('answer_boolean', models.BooleanField(blank=True, null=True)),
                ('answer_integer', models.IntegerField(blank=True, null=True)),
                ('answer_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('answer_text', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='master.questionnaire')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='respondent.respondent')),
            ],
            options={
                'db_table': 'survey_response',
                'ordering': ['respondent'],
            },
        ),
    ]
