# Generated by Django 5.2.16 on 2026-07-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_alter_cluster_code_alter_cluster_name_and_more"),
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyVillage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_villages",
                        to="survey.survey",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="survey_villages",
                        to="master.village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Village",
                "verbose_name_plural": "Survey Villages",
                "db_table": "survey_village",
                "unique_together": {("survey", "village")},
            },
        ),
    ]
