# Generated by Django 5.2.16 on 2026-08-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecommendationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("ranking", models.JSONField(default=list)),
                ("n_villages", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Recommendation Result (cache)",
            },
        ),
    ]
