# Generated by Django 5.2.16 on 2026-08-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbotusage",
            name="month",
            field=models.CharField(
                help_text="Format YYYY-MM", max_length=7, unique=True
            ),
        ),
    ]
