# Generated by Django 5.2.16 on 2026-07-25 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Cluster Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cluster Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('color', models.CharField(default='#0d6efd', max_length=20, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'db_table': 'master_cluster',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='District Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='District Name')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'master_district',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Indicator Code')),
                ('name', models.CharField(max_length=255, verbose_name='Indicator Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Weight')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'db_table': 'master_indicator',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Variable Code')),
                ('name', models.CharField(max_length=200, verbose_name='Variable Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Weight')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
                'db_table': 'master_variable',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer_type', models.CharField(choices=[('boolean', 'Yes / No'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('text', 'Text'), ('choice', 'Multiple Choice')], default='boolean', max_length=20, verbose_name='Answer Type')),
                ('question_order', models.PositiveIntegerField(default=1, verbose_name='Question Order')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='master.indicator', verbose_name='Indicator')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'db_table': 'master_questionnaire',
                'ordering': ['indicator', 'question_order'],
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='master.variable', verbose_name='Variable'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Village Code')),
                ('name', models.CharField(max_length=150, verbose_name='Village Name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='villages', to='master.cluster', verbose_name='Cluster')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villages', to='master.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'db_table': 'master_village',
                'ordering': ['name'],
            },
        ),
    ]
