# Generated by Django 5.2.16 on 2026-07-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="code",
            field=models.CharField(
                db_index=True, max_length=10, unique=True, verbose_name="Cluster Code"
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="Cluster Name"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="code",
            field=models.CharField(
                db_index=True, max_length=10, unique=True, verbose_name="District Code"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="District Name"
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="code",
            field=models.CharField(
                db_index=True, max_length=10, unique=True, verbose_name="Indicator Code"
            ),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=100,
                unique=True,
                verbose_name="Indicator Name",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="code",
            field=models.CharField(
                db_index=True, max_length=10, unique=True, verbose_name="Variable Code"
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="Variable Name"
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="code",
            field=models.CharField(
                db_index=True, max_length=10, unique=True, verbose_name="District Code"
            ),
        ),
        migrations.AlterField(
            model_name="village",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="District Name"
            ),
        ),
    ]
