# Generated by Django 5.2.16 on 2026-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_alter_cluster_code_alter_cluster_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="criterion_type",
            field=models.CharField(
                choices=[("benefit", "Benefit"), ("cost", "Cost")],
                default="benefit",
                max_length=10,
                verbose_name="Criterion Type",
            ),
        ),
    ]
