# Generated by Django 5.2.16 on 2026-08-21 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0005_variable_role_order_layer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VariableConfigAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("reorder", "Reorder"),
                            ("move", "Move"),
                            ("add_layer", "Add Layer"),
                            ("remove_layer", "Remove Layer"),
                            ("deactivate_layer", "Deactivate Layer"),
                            ("activate_layer", "Activate Layer"),
                        ],
                        max_length=30,
                        verbose_name="Action",
                    ),
                ),
                (
                    "old_role",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Old Role"
                    ),
                ),
                (
                    "new_role",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="New Role"
                    ),
                ),
                (
                    "old_order",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Old Order"
                    ),
                ),
                (
                    "new_order",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="New Order"
                    ),
                ),
                (
                    "old_layer",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Old Layer"
                    ),
                ),
                (
                    "new_layer",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="New Layer"
                    ),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, default=dict, verbose_name="Detail"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_audit_logs",
                        to="master.variable",
                        verbose_name="Variable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variable Config Audit Log",
                "verbose_name_plural": "Variable Config Audit Logs",
                "db_table": "master_variable_config_audit",
                "ordering": ["-created_at"],
            },
        ),
    ]
